
//#include <pic18f14k50.h>
#include <stdio.h>
#include <stdlib.h>
#include <xc.h>
#include "config.h"

//pin assign
#define oled_res LATBbits.LATB5
#define testpin LATBbits.LATB7
#define oled_add 0x78   //set oled I2C address + write mode
#define oled_add_r 0x79 //set oled I2C address + read mode
#define oled_command 0x80   //Co bit=1, D/C# bit=0 next data is command
#define oled_data 0x00   //Co bit=0, D/C# bit=0 next data is data
#define oled_ram 0x40   //Co bit=0, D/C# bit=1 next data is graphic data
#define disp_off 0xAE   //oled display off

/* 
 * File:   main.c
 * Author: Yb
 *
 * Created on 2016/07/10, 22:30
 */

void send_i2c(char, char);   //initialize
void wait_1m(int);  //wait time

void interrupt high_isr (void)
{
    //timer count
    
    //
}

void interrupt low_priority low_isr (void)
{
    
}

//set time
void time_setting(void){
    
}

void init(void){
    //Clock set
    OSCCONbits.IRCF = 0x3;  //Internal clock = 2MHz
    //non use module stop
    CM1CON0 = 0x00;     //Compalator disable
    CM2CON0 = 0x00;
    ADCON0bits.ADON = 0;    //A/D converter disable
    ANSEL = 0x00;   //analog stop
    ANSELH = 0x00;  //analog stop
    //GPIO set
    TRISA = 0xFF;   //all pin input
    WPUA = 0x38;    //RP5,4,3 week pull up set
    INTCON2bits.RABPU = 0;  //week pull up enabled
    TRISB = 0x5F;   //RB5 output
    LATBbits.LATB5 = 0;  //OLED RESET pin enabled
    
    //i2c port set(master mode)
    SSPCON1 = 0x08; //master mode set
    //SSPCON2bits.RCEN = 1;   //Receive enable
    SSPSTAT = 0x00; //set 100kHz mode
    SSPADD = 0;    //Baud rate set  Fscl = Fosc / (SSPADD + 1)(4) //2:333kHz 9:100kHz
    SSPCON1bits.SSPEN = 1;  //I2C module start
    //oled_res = 0;  //OLED RESET pin enabled
    testpin = 0;
    
}

//oled start
void oled_open(void){
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0xAE);   //display off
    
    //Set Display Clock Divide Ratio/Oscillator Frequency
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0xD5);
    send_i2c(1,oled_data);   //send controll byte
    send_i2c(2,0x85);
    
    //Set Multiplex Ratio
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0xA8);
    send_i2c(1,oled_data);   //send controll byte
    send_i2c(2,0x1F);
    
    //Set Display Offset
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0xD3);
    send_i2c(1,oled_data);   //send controll byte
    send_i2c(2,0x00);
    
    //Set Display Start Line
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0x40);
    
    //Set Charge Pump
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0x8D);
    send_i2c(1,oled_data);   //send controll byte
    send_i2c(2,0x14);       //0x10:VCC Supplied Externally, 0x14:VCC Generated by Internal DC/DC Circuit
    
    //Set Segment Re-Map
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0xA1);
    
    //Set COM Output Scan Direction
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0xC8);
    
    //Set COM Pins Hardware Configuration
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0xDA);
    send_i2c(1,oled_data);   //i2c address
    send_i2c(2,0x02);
    
    //Set Contrast Control
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0x81);
    send_i2c(1,oled_data);   //i2c address
    send_i2c(2,0xFF);
    
    //Set Pre-Charge Period
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0xD9);
    send_i2c(1,oled_data);   //i2c address
    send_i2c(2,0xF1);       //0x22:VCC Supplied Externally, 0xF1:VCC Generated by Internal DC/DC Circuit
    
    //Set VCOMH Deselect Level
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0xDB);
    send_i2c(1,oled_data);   //i2c address
    send_i2c(2,0x00);
    
    //Set Entire Display On/Off
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0xA4);
    
    //Set Normal/Inverse Display
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0xA6);
    
    //Set Memory addressing mode
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0x20);
    send_i2c(1,oled_data);   //i2c address
    send_i2c(2,0x00);       //set Horizontal Addressing Mode
    
    //Set Page Start Address for Page Addressing Mode
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(1,0x22);
    send_i2c(1,oled_data);   //i2c address
    send_i2c(1,0x00);       //set Page Start Address
    send_i2c(2,0x03);       //set Page End Address
    
    //wait 100msec
    wait_1m(8);
    
    //Set Display On
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0xAF);
}

//send data for i2c
void send_i2c(char status, char data){ //status= 0:start 1:stay 2:end
    //oled_res = 1;  //OLED RESET pin enabled
    switch(status){
        case 0x00:  //start session
            SSPCON2bits.SEN = 1;    //set start 
            while(1){
                if(SSPCON2bits.SEN==0)break;   //if set SSPIF, goto next process
            }
            PIR1 = PIR1 & 0xF7;  //clear flag
            break;
        case 0x01:  //restart session
            //SSPCON2bits.RSEN = 1;    //set start 
            while(1){
                if(SSPCON2bits.RSEN==0)break;   //if set SSPIF, goto next process
            }
            PIR1 = PIR1 & 0xF7;  //clear flag
            break;
        case 0x02:  //if need setting, write below.
            break;
    }
    //testpin = 1;
    SSPBUF = data;  //send data
    PIR1bits.SSPIF = 0;  //clear flag
    while(1){
        if(PIR1bits.SSPIF==1)break;   //if set SSPIF, goto next process
    }
    switch(status){
            case 0x00:  //if need setting, write below.
                break;
            case 0x01:  //if need setting, write below.
                //testpin = 1;
                break;
            case 0x02:
                SSPCON2bits.PEN = 1;    //set stop
                while(1)if(SSPCON2bits.PEN == 0)break;   //if set SSPIF, goto next process
                PIR1bits.SSPIF = 0;  //clear flag
                break;
    }
}

void i2c_stop(void){  //set i2c stop condition
    SSPCON2bits.PEN = 1;    //set stop
    while(1)if(SSPCON2bits.PEN == 1)break;   //if set SSPIF, goto next process
    PIR1bits.SSPIF = 0;  //clear flag
}

//oled stop
void oled_close(void){
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0xAE);   //display off
}

void oled_on(void){
    send_i2c(0,oled_add);   //i2c address
    send_i2c(1,oled_command);   //send controll byte
    send_i2c(2,0xAF);
}

//display picture set
void oled_set(void){
    int row, column,i;
    char data;
    data = 0x00;
    send_i2c(0,oled_add);
    send_i2c(1,oled_ram);   //send controll byte
    for(column = 0;column <= 3;column++){
        //send_i2c(0,oled_add);
        //send_i2c(1,oled_ram);   //send controll byte
        for(row = 0;row <= 127;row++){
            if(i > 7){
                i = 0;
                data = data ^ 0xFF;
            }
            i++;
            send_i2c(1,data);
        }
        data = data ^ 0xFF;
    }
    i2c_stop();
}

//create display picture
void clk_gfx(char type, int hour, int minute, int second){
    
}

void wait(int time){
    int i;
    for(i = 0;i < time;i++);    //wait count
}

void wait_1m(int time){
    int i, j;
    for(i = 0;i < 1000;i++){
        for(j = 0;j < time;j++);    //wait count
    }
}

/*
 * 
 */
int main(int argc, char** argv) {
    int count;
    char port,state;
    state = 0;
    init();      //set IO
    oled_res = 0;  //OLED RESET pin 0
    wait(1000);
    oled_res = 1;  //OLED RESET pin enabled
    //display test
    oled_open();
    //oled_res = 1;  //OLED RESET pin enabled
    //testpin = 1;
    while(1){
        if((state == 0x00) && (PORTAbits.RA5 == 0)){
            oled_set();
            oled_on();
            state = 0x01;
            SLEEP();
        }
        else if((state == 0x01) && (PORTAbits.RA5 == 1)){
            oled_close();
            state = 0x00;
        }
    }
    return (EXIT_SUCCESS);
}

